# file      : bpkg/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs += libbutl%lib{butl}

lib{bpkg}:                               \
{hxx         cxx}{ manifest            } \
{hxx         cxx}{ manifest-parser     } \
{hxx         cxx}{ manifest-serializer } \
{hxx            }{ version             } \
$libs

cxx.poptions += -I$src_root
lib{bpkg}: cxx.export.poptions = -I$src_root
