# file      : bpkg/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import int_libs = libbutl%lib{butl}

lib{bpkg}:                               \
{hxx            }{ export              } \
{hxx         cxx}{ manifest            } \
{hxx            }{ version             } \
                   $int_libs

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $abi_prerelease
  lib{bpkg}: bin.lib.version = @-$version
else
  lib{bpkg}: bin.lib.version = @-$abi_major.$abi_minor

cxx.poptions =+ "-I$src_root"
obja{*}: cxx.poptions += -DLIBBPKG_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBBPKG_SHARED_BUILD

lib{bpkg}: cxx.export.poptions = "-I$src_root"
liba{bpkg}: cxx.export.poptions += -DLIBBPKG_STATIC
libs{bpkg}: cxx.export.poptions += -DLIBBPKG_SHARED

lib{bpkg}: cxx.export.libs = $int_libs

# Install into the bpkg/ subdirectory of, say, /usr/include/.
#
install.include = $install.include/bpkg/
