# file      : bpkg/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs += libhello
lib{bpkg}: cxx{manifest-parser manifest-serializer} $libs
