# file      : tests/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

d = manifest/ package-version/ repository-location/

./: $d
include $d
