# file      : tests/package-version/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver} ../../bpkg/lib{bpkg}

include ../../bpkg/

