# file      : libbpkg/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import int_libs = libbutl%lib{butl}

lib{bpkg}: {hxx ixx txx cxx}{** -version} {hxx}{version} $int_libs

hxx{version}: in{version} $src_root/file{manifest}
hxx{version}: dist = true

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version.
#
if $version.pre_release
  lib{bpkg}: bin.lib.version = @"-$version.project_id"
else
  lib{bpkg}: bin.lib.version = @"-$version.major.$version.minor"

cxx.poptions =+ "-I$out_root" "-I$src_root"
obja{*}: cxx.poptions += -DLIBBPKG_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBBPKG_SHARED_BUILD

lib{bpkg}: cxx.export.poptions = "-I$out_root" "-I$src_root"
liba{bpkg}: cxx.export.poptions += -DLIBBPKG_STATIC
libs{bpkg}: cxx.export.poptions += -DLIBBPKG_SHARED

lib{bpkg}: cxx.export.libs = $int_libs

# Install into the libbpkg/ subdirectory of, say, /usr/include/.
#
{hxx ixx txx}{*}: install = include/libbpkg/
