# file      : tests/build-class-expr/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs  = libbutl%lib{butl}
import libs += libbpkg%lib{bpkg}

exe{driver}: {hxx cxx}{*} $libs testscript
