# file      : tests/repository-location/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs += libbutl%lib{butl}

exe{driver}: cxx{driver} ../../libbpkg/lib{bpkg} $libs

include ../../libbpkg/
