# file      : tests/repository-location/buildfile
# copyright : Copyright (c) 2014-2016 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs += libbutl%lib{butl}

exe{driver}: cxx{driver} ../../bpkg/lib{bpkg} $libs

include ../../bpkg/
