# file      : tests/manifest/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs += libbutl%lib{butl}

exe{driver}: cxx{*} ../../libbpkg/lib{bpkg} $libs test{testscript}

include ../../libbpkg/
