# file      : tests/manifest/buildfile
# copyright : Copyright (c) 2014-2017 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import libs  = libbutl%lib{butl}
import libs += libbpkg%lib{bpkg}

exe{driver}: {hxx cxx}{*} $libs test{testscript}
