# file      : tests/manifest-roundtrip/buildfile
# copyright : Copyright (c) 2014-2015 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver} ../../bpkg/lib{bpkg}
exe{driver}: test.roundtrip = manifest

include ../../bpkg/
